version: "3"
services:
  web:
    build: .
    environment:
      TZ: "Asia/Tokyo"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true
